# wrangler.toml
name = "python-data-analysis-platform"
type = "javascript"

account_id = "${CLOUDFLARE_ACCOUNT_ID}"
workers_dev = true

[env.production]
name = "python-data-analysis-platform"

# 环境变量
[vars]
CLOUDFLARE_ACCOUNT_ID = ""
AI_GATEWAY_NAME = ""
AI_API_KEY = ""


